import { 
  LayoutDashboard, 
  Users, 
  Calculator, 
  Briefcase, 
  FolderKanban, 
  ShoppingCart, 
  Store, 
  HeadphonesIcon,
  AlertCircle,
  TrendingUp,
  ShieldCheck,
  Coffee,
  ShoppingBag,
  Shirt,
  Zap,
  CreditCard,
  WifiOff,
  Split,
  Receipt,
  Map,
  Boxes,
  ClipboardCheck,
  ArrowRightLeft,
  Bell,
  ChefHat,
  Truck,
  BookOpen,
  PieChart,
  Wallet,
  Landmark,
  FileSpreadsheet,
  ScanFace,
  Trophy,
  CalendarClock,
  Gift,
  Tags,
  Database,
  Video,
  MessageSquare,
  FileText,
  Clock,
  Bug,
  Calendar,
  Target,
  UserPlus,
  GraduationCap,
  Award,
  Settings,
  BarChart3,
  Globe,
  Smartphone
} from 'lucide-react';

// Icons mapping for the dynamic features component
export const FEATURE_ICONS: Record<string, any> = {
  // POS
  fast_checkout: Zap,
  multi_payment: CreditCard,
  table_management: Map,
  offline_mode: WifiOff,
  split_bill: Split,
  digital_receipt: Receipt,
  
  // Inventory
  multi_warehouse: Boxes,
  stock_opname: ClipboardCheck,
  stock_transfer: ArrowRightLeft,
  low_stock: Bell,
  raw_materials: ChefHat,
  supplier: Truck,

  // Finance
  auto_journal: BookOpen,
  realtime_pnl: PieChart,
  expense: Wallet,
  cash_flow: TrendingUp,
  tax: Landmark,
  reconciliation: FileSpreadsheet,
  budget: Calculator,
  invoice: FileText,

  // HRM
  attendance: ScanFace,
  payroll: Trophy,
  shift: CalendarClock,
  recruitment: UserPlus,
  training: GraduationCap,
  performance: Award,
  leave: Calendar,

  // CRM
  leads: Users,
  deals: Target,
  contract: FileText,
  customer_db: Database,
  messenger: MessageSquare,
  
  // Project
  project_mgmt: FolderKanban,
  tasks: Briefcase,
  timesheet: Clock,
  bug_tracker: Bug,
  
  // Support & System
  zoom: Video,
  settings: Settings,
  reports: BarChart3,
  mobile: Smartphone
};